name: distiller-env-parse2
channels:
    - conda-forge               
    - defaults                  
    - bioconda                  
    - golobor
dependencies:
    - python=3.7
    - parallel
    - pbgzip
    - lz4-c
    - samtools>=1.4
    - sra-tools>=2.8.1
    - fastqc
    - bwa
    - seqtk
    - setuptools 
    - pip
    - cython 
    - numpy 
    - dask
    - nose 
    - pairix
    - fastp
    - pysam
    - pip:
        - cooler>=0.8.5
        - toolz
        - git+https://github.com/open2c/pairtools.git@parse2
